### ISSUE TITLE
!

### ISSUE THREAD

**Issue by Colorfingers** [cloud-ark/kubeplus#1025]

**Comment by devdattakulkarni** [comment]
Hi @Colorfingers I am very sorry about your experience. You got caught in the middle of some recent significant changes happening in KubePlus. Some of our examples and documentation have not yet been fully updated with the changes that have happened to the codebase. Probably you stumbled upon those - very sorry you had to go through those.

Let me help you.

Our main README and the examples linked from there should work. Did you try those examples? The helloworld service example is the simplest one and covers the main features of KubePlus. I would recommend trying that example first. As for the installation instructions - you are right. The Helm install command should work (and is the only method we will support going forward). Please disregard other scripts that are available in the deploy folder. As part of the cleanup that we are doing, those will be removed.

I am also available directly via email - devdatta at cloudark dot io. Feel free to email me. You can also ping me on our Slack channel. The invite is in the README.

I want to fix your experience with KubePlus. So anything that I can do - please let me know.

**Comment by Colorfingers** [comment]
Wow, thank you for responding... I've found a number of READMEs... and I'm going through the Docs setup in the html folder... I am very grateful that you would take time to help me... let me regroup and reset my cluster.  I'll start again and see where I'm at.. sorry for my frustration.

**Comment by devdattakulkarni** [comment]
@Colorfingers I see - yeah, the different READMEs and steps.txt can seem confusing. Basically, for almost every example we have README and steps.txt. The confusing part can be knowing which examples are accurate as far as the current code base is concerned. For this, we use the top-level README points. It points to working examples. Anything not directly linked from the top-level README, you can ignore. As part of our cleanup, we will be removing examples that are no longer relevant. Just that, we have not had a chance to do that yet. It can lead to a frustrating experience, like yours. Again, sorry you had to go through that.

Once your cluster is reset, I would recommend trying the HelloWorldService example linked from the main README.

And please keep me posted - either here, on Slack, or by email. Let's make sure that KubePlus is working for you.

**Comment by devdattakulkarni** [comment]
@Colorfingers Hi!
We are starting KubePlus community meetings next week. They will be on Tuesdays at 10.30 a.m. US Central time. The meetings will be on #kubeplus Slack channel in the CNCF workspace. I hope you are able to join us for these meetings as we look forward to building KubePlus further with community inputs and involvement.
