### ISSUE TITLE
Bug in dryrunchart

### ISSUE THREAD

**Issue by enyachoke** [cloud-ark/kubeplus#1106]
I found an issue in the dryrunchart endpoint. This line https://github.com/cloud-ark/kubeplus/blob/a1068146c36e1b1715061e5b5206b87aeb1e9d3a/deploy/kubeconfiggenerator.py#L704  does not consider when you provide a chart from a URL. I made an attempt to fix but the endpoint was crashing. I did not but in more time because my dev cycle is long at the moment I have to build and publish the image via actions before I can test

**Comment by devdattakulkarni** [comment]
Ack. I have a fix in the works that should address this. I will be pushing it out in a bit.
