### ISSUE TITLE
HelloWorldService CRD not created

### ISSUE THREAD

**Issue by enyachoke** [cloud-ark/kubeplus#1107]
After doing the workaround for https://github.com/cloud-ark/kubeplus/issues/1106. I finally got everything running and tried to create http://kubeplus-docs.s3-website-us-west-2.amazonaws.com/html/sample-example.html#provider-action  the composition appears to have been created but I don't see the CRD for HelloWorldService.

**Comment by devdattakulkarni** [comment]
Ack. I have a fix in the works that should address this. I will be pushing it out in a bit.
