### ISSUE TITLE
can't query metrics with the kubectl plugin

### ISSUE THREAD

**Issue by sgandon** [cloud-ark/kubeplus#1149]
here is the error
```
❯ kubectl metrics HelloWorldService hs1 kubeplus -k kubeplus-saas-provider.json
  File "//Users/foo/git-repos/kubeplus/plugins/crmetrics.py", line 811
    oom_events = 0
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by devdattakulkarni** [comment]
@sgandon Ack.

**Comment by devdattakulkarni** [comment]
@sgandon Hi!
I wanted to let you know that we will be starting KubePlus community meetings from next week. The meetings will on Tuesdays at 10.30 a.m. US Central time. We will be using Slack huddle on #kubeplus channel in CNCF workspace.
I am hoping that you are able to join us for these meetings as we look forward to building KubePlus with community inputs and involvement.
