### ISSUE TITLE
Follow Kubernetes naming convention for Service (CRD) name and service instance names

### ISSUE THREAD

**Issue by devdattakulkarni** [cloud-ark/kubeplus#1218]
When creating service instances through consumer UI, we should enforce that the service instance name adheres to the following convention: alphanumeric or hyphen with the initial letter not being a hyphen. These are the constraints that are defined by Kubernetes for defining namespaces. The reason we want to set these constraints for defining the service instance names as well is that KubePlus will create a namespace with the service name and then deploy the service Helm chart in that namespace. So we want to make sure that the service name adheres to the naming policies for Kubernetes Namespaces.

**Comment by devdattakulkarni** [comment]
The modifications will be in mutating-webhook:
https://github.com/cloud-ark/kubeplus/blob/master/mutating-webhook/webhook.go
Specifically, check the "trackCustomAPIs" function.

Pre-requisites:
- Understanding of KubePlus architecture
- Understanding of Golang
- Understanding of Kubernetes naming convention.

**Comment by devdattakulkarni** [comment]
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/

We should implement the following checks:
- contain no more than 253 characters
- contain only lowercase alphanumeric characters, '-' or '.'
- start with an alphanumeric character
- end with an alphanumeric character

**Comment by omgoswami** [comment]
Are these checks supposed to be implemented on the `platformWorkflowName` variable in the `trackCustomAPIs` function (line 982)?

**Comment by devdattakulkarni** [comment]
@omgoswami Yes ^^ that is the correct place to add these checks.

**Comment by omgoswami** [comment]
Seems that Kubernetes already checks this for us, and no additional code needs to be written to enforce validity of service instance names. K8s refers to such an instance as a "lowercase RFC 1123 subdomain", and will not allow users to create instances with names that contain uppercase/nonalphanumeric characters, start with a hyphen, etc.

**Comment by devdattakulkarni** [comment]
Thanks @omgoswami for the update.
