### ISSUE TITLE
Remove reference for parse-api-server-url.sh from README

### ISSUE THREAD

**Issue by devdattakulkarni** [cloud-ark/kubeplus#1283]
Recently we got rid of the parse-api-server-url.sh script. But a reference to it still exists in the README (step 4).

We need to update this step.

**Comment by devdattakulkarni** [comment]
@chiukapoor Can you take a look at this issue? It should be straightforward to fix.

**Comment by chiukapoor** [comment]
> @chiukapoor Can you take a look at this issue? It should be straightforward to fix.

Sure
