### ISSUE TITLE
Remove reference to parse-api-server-url.sh from examples

### ISSUE THREAD

**Issue by devdattakulkarni** [cloud-ark/kubeplus#1288]
Recently, we removed the parse-api-server-url.sh script and replaced it with the following more idiomatic way of obtaining the API Server URL for the Kubernetes cluster.

`apiserver=`kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}'`

But there are still references to parse-api-server-url.sh in the examples.
- https://github.com/cloud-ark/kubeplus/blob/master/examples/multitenancy/application-hosting/wordpress/steps.txt#L26
- https://github.com/cloud-ark/kubeplus/blob/master/examples/multitenancy/application-hosting/odoo/steps.txt#L19
- https://github.com/cloud-ark/kubeplus/blob/master/examples/multitenancy/hello-world/steps.txt#L30
- https://github.com/cloud-ark/kubeplus/blob/master/examples/multitenancy/platform-engineering/steps.txt#L21

We should update all the above places to use the idiomatic approach of obtaining the API Server URL.

**Comment by dsuleimenov** [comment]
Hi @devdattakulkarni!
Could you please review my changes regarding to the current issue?

**Comment by devdattakulkarni** [comment]
@dsuleimenov Thanks!! I will review it later today.

**Comment by devdattakulkarni** [comment]
@dsuleimenov Your PR with changes to steps.txt in various example folders looked good. I have merged it.
For the help text change in provider-kubeconfig.py, can you open another PR? You can modify it to the text as you have mentioned in the above comment.

**Comment by devdattakulkarni** [comment]
@dsuleimenov I have merged the new PR.

Thanks for your PRs. Please join us on kubeplus Slack channel to participate in project discussions.
