### ISSUE TITLE
no openapi getter 

### ISSUE THREAD

**Issue by Aminechouchene98** [cloud-ark/kubeplus#1333]
when creating the provider kubeconfig using provider-kubeconfig.py after this command 
python3 provider-kubeconfig.py -s $apiserver create $KUBEPLUS_NS 
i get this error 
b'error: no openapi getter\n'

**Comment by devdattakulkarni** [comment]
@Aminechouchene98 Strange. Did you get this error by following the steps from the README?
Can you share your environment details?

**Comment by Aminechouchene98** [comment]
Ubuntu 22.04.4 LTS
server version v1.28.11.+rke2r1
client version v1.28.11+rke2r1

**Comment by Aminechouchene98** [comment]
python3 --version
Python 3.10.12
which kubectl
/usr/local/bin/kubectl
kubectl version
Client Version: v1.28.11+rke2r1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
server version v1.28.11.+rke2r1

**Comment by devdattakulkarni** [comment]
@Aminechouchene98 Can you share the location of the default kubeconfig file on your RKE environment?

`usage: provider-kubeconfig.py [-h] [-k KUBECONFIG] [-s APISERVERURL]
                              [-f FILENAME] [-p PERMISSIONFILE]
                              {create,delete,update,extract} namespace
`
You can pass the full path of the kubeconfig file with '-k' flag when creating the provider kubeconfig.

**Comment by Aminechouchene98** [comment]
it worked after passing the kubeconfig
