### ISSUE TITLE
Development and Testing WiKi modification require

### ISSUE THREAD

**Issue by rahulkumar-choudhary** [cloud-ark/kubeplus#1355]
### Modification requirement:

- A file named `parse-api-server-url.sh` is not available in the repository directory. A command in the Install KubePlus section requires this file,

```bash
apiserver=`./parse-api-server-url.sh`
```
- Proper explanation for two sections is needed (for understanding internal and independent component working):
    1. Build components 
    2. Install KubePlus

**Comment by devdattakulkarni** [comment]
@rahulkumar-choudhary I have updated the Wiki page.
https://github.com/cloud-ark/kubeplus/wiki/Development-and-Testing

Please check. I have added a small blurb about the development and testing procedure. Let me know if the explanation is sufficient, or if some more additions/clarifications will help.

**Comment by rahulkumar-choudhary** [comment]
@devdattakulkarni , The description explains each component development process clearly now. 

#### I have following points which I came across at the time of development in my local machine, 

###1. While installing KubePlus - 

```bash
python3 provider-kubeconfig.py -s $apiserver create $KUBEPLUS_NS
```

the command contains a `provider-kubeconfig.py` file which contains libraries like `yaml` and the command gives error at the time of running if the yaml library is not present, so my suggestion would be to include appropriate step in the `Development and Testing WiKi` page as a prerequisit.

```bash
pip install pyyaml
```

###2. Clarity on which values to pass for each build component as a parameter in the `helm install` command.

I understand the `$KUBEPLUS_HOME/deploy/kubeplus-chart/values.yaml` file contains the parameter for each build component, but it would be better for visibility and understanding of all the different components of KubePlus, that we mention each as a note in the `Development and Testing WiKi` page.

```bash
# use the following parameters for each KubePlus components,

MUTATING_WEBHOOK
WEBHOOK_INIT_CONTAINER
CRD_REGISTRATION_HELPER
PLATFORM_OPERATOR
CONSUMERUI
HELMER
RESOURCE_CLEANER
```

**Comment by devdattakulkarni** [comment]
💯 @rahulkumar-choudhary 
I will incorporate these changes.

**Comment by devdattakulkarni** [comment]
@rahulkumar-choudhary I have made these updates. Pls take a look and let me know if it is now clear.

**Comment by rahulkumar-choudhary** [comment]
@devdattakulkarni , All the details for development in local machine using the `Development and Testing WiKi`  reference are clear now. 

We can close this issue.

**Comment by devdattakulkarni** [comment]
👍
