### ISSUE TITLE
Readme update require for proper visibility of examples and remove duplication in steps.txt

### ISSUE THREAD

**Issue by SuyogShinde942** [cloud-ark/kubeplus#1358]
The current README file in the KubePlus repository has limited visibility for examples, making it challenging for users to find practical use cases . Additionally, the steps.txt file contains duplicated installation steps, which can be simplified by referencing the main README.

Proposed Changes:
Improve Example Visibility in README:

Add a dedicated section for examples within the README file.

**Streamline Installation Instructions:**

Remove duplicated installation instructions from steps.txt.
Add a brief statement in steps.txt to redirect users to the main README for installation details, ensuring consistency and reducing maintenance efforts

**Comment by devdattakulkarni** [comment]
👍
