### ISSUE TITLE
Not able to access the moodle1 url from host machine.

### ISSUE THREAD

**Issue by rkatti** [cloud-ark/kubeplus#174]
Moodle Operator: Steps Tested with minikube. 

OS and Version : 

System Memory : 8 GB
Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
Kernel release : Linux ubuntu 4.15.0-42-generic 
Kernel :  #45-Ubuntu SMP 
x86_64

Minikube v0.30.0 
Helm v2.11.0

Result : 

Able to bring all the pods up. ( operator, MySQL, and moodle1 ) 
moodle1 pod took a long time more than 2 hours to be ready. 

/etc/host is updated with the IP address and got the admin and password 

but not able to connect to the URL from the host machine. 

http://moodle1:32000
IP: 192.168.99.100 

Is there are any step missing in the doc?

**Comment by devdattakulkarni** [comment]
Can you share the SHA of moodle operator image on your machine?

You will need to run following commands for that:
eval $(minikube docker-env)
docker inspect --format='{{index .RepoDigests 0}}' lmecld/kube-discovery-apiserver

**Comment by rkatti** [comment]
I am able to access the url now and update the plugins. Thanks
