### ISSUE TITLE
No resources found for "mysql-operator-0.2.1" namespace. 

### ISSUE THREAD

**Issue by rkatti** [cloud-ark/kubeplus#178]
~/kubeplus/examples/mysql$ kubectl get pods -n mysql-operator-0.2.1
No resources found.

But when tried to get pods on namespace "mysql-operator" it worked. 

~/kubeplus/examples/mysql$ kubectl get pods -n mysql-operator
NAME                              READY   STATUS    RESTARTS   AGE
mysql-operator-56cb675b7f-szmj8   1/1     Running   0          6m

**Comment by devdattakulkarni** [comment]
Good catch @rkatti
