### ISSUE TITLE
moodle2 instance deploy : status ImagePullBackOff 

### ISSUE THREAD

**Issue by rkatti** [cloud-ark/kubeplus#180]
~/kubeplus/examples/moodle$ kubectl create -f moodle2.yaml

moodle.moodlecontroller.kubeplus/moodle2 created

~/kubeplus/examples/moodle$ kubectl get pods

![screenshot from 2018-12-10 18-44-44](https://user-images.githubusercontent.com/3044030/49734891-b4ef7800-fcab-11e8-8fed-5db0de85a279.png)

**Comment by rkatti** [comment]
~/kubeplus/examples/moodle$ kubectl describe moodles moodle2
Name:         moodle2
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  moodlecontroller.kubeplus/v1
Kind:         Moodle
Metadata:
  Cluster Name:        
  Creation Timestamp:  2018-12-12T01:58:09Z
  Generation:          1
  Resource Version:    2309
  Self Link:           /apis/moodlecontroller.kubeplus/v1/namespaces/default/moodles/moodle2
  UID:                 5fc737b6-fdb1-11e8-84a9-080027e521f9
Spec:
  Name:  moodle2
  Plugins:
    profilecohort
Events:  <none>

**Comment by devdattakulkarni** [comment]
@rkatti Thanks! If you still have the environment, can you also share output of following command:
kubectl describe pods <moodle2-pod>
