### ISSUE TITLE
Handling Operator CRD and children resource ownership across KubePlus deployments

### ISSUE THREAD

**Issue by danielpygo** [cloud-ark/kubeplus#197]
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

$ minikube version
minikube version: v0.28.2

OS:
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54

$ kubectl delete -f moodle-operator.yaml
Error from server (NotFound): error when deleting "moodle-operator.yaml": operators.operatorcontroller.kubeplus "moodle-operator" not found

$ kubectl get operators
No resources found.

$ kubectl get pods
NAME                                          READY     STATUS    RESTARTS   AGE
kubeplus-gkhhk                                4/4       Running   0          39s
moodle-operator-deployment-64cdcb958c-j5wdr   1/1       Running   0          16m

$ kubectl logs moodle-operator-deployment-64cdcb958c-j5wdr
**************************************
Moodle Name:moodle1
Plugins:[profilecohort]
Inside deployMoodle
Inside createPersistentVolume
Creating persistentVolume...
Created persistentVolume "moodle1".
Inside createPersistentVolumeClaim
Creating persistentVolumeClaim...
Created persistentVolumeClaim "moodle1".
Inside createService
Created service "moodle1".
Moodle Service IP:%s 10.111.160.190
Service URI10.111.160.190:32000
Creating Ingress...
Created Ingress "moodle1".
Inside createDeployment
Generated Password:0PIgyQbQ
Inside createSecret
Secret Name:moodle1
Admin Password:0PIgyQbQ
Creating secrets..
Created Secret "moodle1".
MySQL Service Port int:%d
 3306
MySQL Service Port:%d
 3306
MySQL Host IP:%s
 10.108.57.105
HOST_NAME:%s
 moodle1:32000
Creating deployment...
Created deployment "moodle1".
Waiting for Moodle Pod to get ready.
Moodle Pod Name:moodle1-76dbff7b5c-ccg55
Waiting for Moodle Pod to get ready.
Moodle Pod Name:moodle1-76dbff7b5c-ccg55
...
Waiting for Moodle Pod to get ready.
Moodle Pod Name:moodle1-76dbff7b5c-ccg55
Waiting for Moodle Pod to get ready.
Moodle Pod Name:moodle1-76dbff7b5c-ccg55
Waiting for Moodle Pod to get ready.
Moodle Pod Name:moodle1-76dbff7b5c-ccg55
Waiting for Moodle Pod to get ready.
Moodle Pod Name:moodle1-76dbff7b5c-ccg55
Moodle Pod is running.
Pod is ready.
Supported Plugins:%v [profilecohort]
Unsupported Plugins:%v []
Inside installPlugins
Installing plugin profilecohort
Download Link:https://moodle.org/plugins/download.php/17929/local_profilecohort_moodle35_2018092800.zip
Install Folder:/var/www/html/local/
Inside exec
Plugin ZipFile Name:local_profilecohort_moodle35_2018092800.zip
Download Plugin Cmd:wget https://moodle.org/plugins/download.php/17929/local_profilecohort_moodle35_2018092800.zip -O /tmp/local_profilecohort_moodle35_2018092800.zip
Inside executeExecCall
Output:
Unzip Plugin Cmd:unzip /tmp/local_profilecohort_moodle35_2018092800.zip -d /tmp/.
Inside executeExecCall
Output:Archive:  /tmp/local_profilecohort_moodle35_2018092800.zip
   creating: profilecohort/
  inflating: profilecohort/styles.css
   creating: profilecohort/classes/
  inflating: profilecohort/classes/profilecohort.php
   creating: profilecohort/classes/task/
  inflating: profilecohort/classes/task/update_cohorts.php
  inflating: profilecohort/classes/profilefields.php
   creating: profilecohort/classes/privacy/
  inflating: profilecohort/classes/privacy/provider.php
  inflating: profilecohort/classes/field_checkbox.php
  inflating: profilecohort/classes/field_text.php
  inflating: profilecohort/classes/field_textarea.php
  inflating: profilecohort/classes/field_menu.php
  inflating: profilecohort/classes/cohort_form.php
  inflating: profilecohort/classes/fields_form.php
  inflating: profilecohort/classes/field_base.php
  inflating: profilecohort/CHANGES.md
  inflating: profilecohort/.travis.yml
   creating: profilecohort/lang/
   creating: profilecohort/lang/en/
  inflating: profilecohort/lang/en/local_profilecohort.php
   creating: profilecohort/amd/
   creating: profilecohort/amd/src/
  inflating: profilecohort/amd/src/reorder.js
   creating: profilecohort/amd/build/
  inflating: profilecohort/amd/build/reorder.min.js
  inflating: profilecohort/COPYING.txt
   creating: profilecohort/tests/
  inflating: profilecohort/tests/rules_test.php
   creating: profilecohort/tests/behat/
  inflating: profilecohort/tests/behat/edit_rules.feature
  inflating: profilecohort/tests/behat/behat_local_profilecohort.php
  inflating: profilecohort/index.php
  inflating: profilecohort/cohorts.php
   creating: profilecohort/db/
  inflating: profilecohort/db/events.php
  inflating: profilecohort/db/upgrade.php
  inflating: profilecohort/db/tasks.php
  inflating: profilecohort/db/install.xml
  inflating: profilecohort/version.php
  inflating: profilecohort/settings.php
  inflating: profilecohort/README.md

Move Plugin Cmd:mv /tmp/profilecohort /var/www/html/local//.
Inside executeExecCall
Output:
Done installing plugin profilecohort
Erred Plugins:[]
Done installing Plugins
Returning from deployMoodle
Moodle URL:http://moodle1:32000
**************************************
Moodle Name:moodle1
Plugins:[profilecohort]
Spec Plugins:[profilecohort]
Installed Plugins:[profilecohort]
Plugins to install:%v
 []
Plugins to remove:%v
 []
Supported Plugins:%v []
Unsupported Plugins:%v []
Moodle custom resource moodle1 did not change. No plugin installed.

**Logs:**

$ kubectl logs -c kube-discovery-apiserver
error: expected 'logs (POD | TYPE/NAME) [CONTAINER_NAME]'.
POD or TYPE/NAME is a required argument for the logs command
See 'kubectl logs -h' for help and examples.
same output for others...
$ kubectl logs -c operator-deployer

$ kubectl logs -c operator-manager

So this issue may be because I did delete the deploy/ directory before I tried to delete the moodle-operator-deployment pod. But now, when I re-applied the kubeplus 4/4 pods, I can no longer see the operator or delete this pod anymore . See command inputs:

```

$ kubectl get pods
NAME                                          READY     STATUS    RESTARTS   AGE
kubeplus-gkhhk                                4/4       Running   0          8m
moodle-operator-deployment-64cdcb958c-j5wdr   1/1       Running   0          24m

$ kubectl delete -f moodle-operator.yaml
Error from server (NotFound): error when deleting "moodle-operator.yaml": operators.operatorcontroller.kubeplus "moodle-operator" not found


```

YAMLS: moodle-operator.yaml
Image Tags for: Operator-Manager

**Comment by devdattakulkarni** [comment]
So couple of things:
1. There is no need to delete the deploy/ directory ever. That directory contains all the deployment related artifacts of kubeplus itself. It does not include anything related to any operator.

2. In order to delete the moodle operator the command is:
kubectl delete operators moodle-operator

3. Once kubeplus pods are deleted then the 'operator' custom resource will not be available in the cluster. In above case once you have reapplied kubeplus the 'operator' custom resource should be registered again. But I am guessing that because the moodle-operator was 'known' to the previous version of kubeplus, it is not able to find it even though it exists.

I think this bring a bigger issue of how to handle/garbage collect/transfer ownership of operators and their resources across kubeplus deployments.

I will change the title of this issue to reflect above point.

**Comment by devdattakulkarni** [comment]
Operator CRD has been deprecated.

https://github.com/cloud-ark/kubeplus/releases/tag/0.3.0
