### ISSUE TITLE
How do status type get updated

### ISSUE THREAD

**Issue by barry-schneider** [cloud-ark/kubeplus#21]
Where is the code for the controller to update the status type?

	AvailableReplicas int32 `json:"availableReplicas"`
	ActionHistory []string `json:"actionHistory"`
	Users []UserSpec `json:"users"`
	Databases []string `json:"databases"`
	VerifyCmd string `json:"verifyCommand"`
	ServiceIP string `json:"serviceIP"`
	ServicePort string `json:"servicePort"`
	Status string `json:"status"`

**Comment by devdattakulkarni** [comment]
@barry-schneider Thanks for the question.

The CRD's overall Spec status is updated in following function:
https://github.com/cloud-ark/kubeplus/blob/master/postgres-crd-v2/controller.go#L418

In the Spec, there is a 'Status' field which is used to capture the working state of the resource. It is updated in:
https://github.com/cloud-ark/kubeplus/blob/master/postgres-crd-v2/controller.go#L436

Let me know if that helps.

**Comment by barry-schneider** [comment]
Thank you that is very helpful.
