### ISSUE TITLE
Etcd_helper functionality for saving operator data

### ISSUE THREAD

**Issue by danielpygo** [cloud-ark/kubeplus#222]
https://github.com/cloud-ark/kubeplus/blob/master/operator-manager/controller.go#L429

```go


func saveOperatorData(operatorName string, crds []string, operatorOpenAPIConfigMapName string) {

	resourceKey := "/operators"
	var operatorDataMap = make(map[string]interface{})
	var operatorMap = make(map[string]map[string]interface{})
	var operatorMapList = make([]map[string]map[string]interface{}, 0)

	operatorDataMap["Name"] = operatorName
	operatorDataMap["CustomResources"] = crds
	operatorDataMap["ConfigMapName"] = operatorOpenAPIConfigMapName

	operatorMap["Operator"] = operatorDataMap

	operatorMapList = append(operatorMapList, operatorMap)

	storeEtcd(resourceKey, operatorMapList)

```

StoreEtcd needs a Store and Get method for type []map[string]map[string]interface{}

Also a test method

But @devdattakulkarni , it seems like this slice is always of size 1 since you just initialized it and appended one thing. Could this be simplified?
I believe it is still needed in etcd_helper because it seems like you are definitely expected a list of operators in kubediscovery, since you have a loop over such a map slice

**Comment by devdattakulkarni** [comment]
Closing this as operator-manager is no longer being used to deploy Operator helm charts. Instead, we are using
