### ISSUE TITLE
Add kubediscovery as submodule

### ISSUE THREAD

**Issue by danielpygo** [cloud-ark/kubeplus#225]
https://git-scm.com/book/en/v2/Git-Tools-Submodules
I think it would be good to add kubediscovery as a submodule to this project, since it is part of the deploy/ folder

Can simplify some scripts and steps, also if you cd into the submodule, you would interact with git normally 

Issues would still be filed to the kubediscovery project. kubeplus/master would always be working with the up-to-date kubediscovery/master whenever we git pull

**Comment by devdattakulkarni** [comment]
We should definitely do this.

What is required for this?? Can you do a WIP PR (Work-in-Progress)? We can work from there.

**Comment by danielpygo** [comment]
It's simple, I've done it once before 
`git submodule add git@github.com:url_to/awesome_submodule.git path_to_awesome_submodule`
`git submodule init`
After there commits are done to kubediscovery, this is the correct command to use not (git pull)
`git submodule update`

[reference](https://gist.github.com/gitaarik/8735255)

Also:
I think it is best to deal with commits and branches, inside of the cloud-ark/kubediscovery codebase

**Comment by devdattakulkarni** [comment]
We have removed the discovery folder as it was cluttering the folder structure without providing enough direct value. We can bring it back if there are any specific components that we can put inside that folder.
