### ISSUE TITLE
Should path in v2 readme refer to v2

### ISSUE THREAD

**Issue by barry-schneider** [cloud-ark/kubeplus#24]
In the steps listed for the [Actual steps (Minikube)](https://github.com/cloud-ark/kubeplus/blob/master/postgres-crd-v2/README.rst#actual-steps-minikube) the paths are using

`$GOPATH/src/github.com/cloud-ark/kubeplus/postgres-crd `

Should they be using the v2 path?

`$GOPATH/src/github.com/cloud-ark/kubeplus/postgres-crd-v2`

**Comment by devdattakulkarni** [comment]
Good catch! If you create a PR I will be happy to merge it.

**Comment by devdattakulkarni** [comment]
Fixed in https://github.com/cloud-ark/kubeplus/pull/26
