### ISSUE TITLE
Deploy kubeplus error: ImagePullBackOff

### ISSUE THREAD

**Issue by danielpygo** [cloud-ark/kubeplus#240]
In deploy/rc.yaml
when I changed it to:
```
      - name: kube-discovery-apiserver
        image: kube-discovery-apiserver:latest
```
it deployed.

So It is either the image tag, or that you did not put the image on docker hub

**Comment by devdattakulkarni** [comment]
Appropriate image tag was not pushed to DockerHub. This has been fixed now.
