### ISSUE TITLE
Directory structure

### ISSUE THREAD

**Issue by barry-schneider** [cloud-ark/kubeplus#25]
I am just trying to understand the directory structure for this project. Especially the .go files under https://github.com/cloud-ark/kubeplus/tree/master/postgres-crd-v2

**Comment by devdattakulkarni** [comment]
main.go -> Starting point
controller.go -> Controller code for Postgres CRD
user.go -> Functions for performing User related actions on a Postgres instance
database.go -> Functions for performing Database related actions on a Postgres instance
utils.go -> Utility functions

./postgres-crd-v2/pkg/apis/postgrescontroller/v1/types.go -> Definition of Postgres CRD spec

**Comment by barry-schneider** [comment]
The structure on the [kubernetes sample controller issue 14](https://github.com/cloud-ark/kubeplus/issues/14) has the Controller's logic in another location. I am not sure where these files should live but in the root does not feel right. What do you think?

**Create the Controller's logic**
Now that all the required code has been generated we've got ourselves some nice options to perform some routine tasks:

./pkg/client/clientset/versioned/typed/samplecontroller/v1alpha1/samplecontroller_client.go which will act as our goto-structure to access any api-endpoint related to the CustomResource we created.

./pkg/client/clientset/versioned/typed/samplecontroller/v1alpha1/foo.go which will add the .Foo("<supply a namespacehere>") which in turn supplies an interface to operations like:

- List
- Get
- Watch

**Comment by devdattakulkarni** [comment]
Rather than refactoring postgres-crd-v2, we can consider these points in any new Operator/custom controller that we will create.

Steps to create new custom controller are included in:
https://github.com/cloud-ark/kubeplus/blob/master/docs/setup/creating-operator.txt

One of the things that can be considered as part of this process is location of the source code files.

So closing this issue.
