### ISSUE TITLE
What is KubeARK

### ISSUE THREAD

**Issue by barry-schneider** [cloud-ark/kubeplus#27]
KubeARK is reference in the readme but I am not able to find any code or github project.

**Comment by devdattakulkarni** [comment]
We are working on it and will updating the repo with more information on it soon.

**Comment by devdattakulkarni** [comment]
@barry-schneider We now have one piece of the erstwhile KubeARK. 

https://github.com/cloud-ark/kubeprovenance

Let me know any feedback/comments.

**Comment by devdattakulkarni** [comment]
First cut of KubePlus platform kit is available. Here are the steps to try it out:
https://github.com/cloud-ark/kubeplus/blob/master/kubeplus-steps.txt

**Comment by devdattakulkarni** [comment]
@barry8schneider Hi!
We are starting KubePlus community meetings next week. They will be on Tuesdays at 10.30 a.m. US Central time. The meetings will be on #kubeplus Slack channel in the CNCF workspace. I hope you are able to join us for these meetings as we look forward to building KubePlus further with community inputs and involvement.
