### ISSUE TITLE
Extend AddLabel to support more resources

### ISSUE THREAD

**Issue by danielpygo** [cloud-ark/kubeplus#302]
https://github.com/cloud-ark/kubeplus/blob/master/mutating-webhook/utils.go#L124
Currently AddLabel only supports labeling Deployment objects. Should extend this to other types .

**Comment by devdattakulkarni** [comment]
+1

**Comment by devdattakulkarni** [comment]
We are now using client-go's Unstructured package for querying/updating resources generically.
