### ISSUE TITLE
KubeDB?

### ISSUE THREAD

**Issue by tamalsaha** [cloud-ark/kubeplus#32]
Hey,
Have you checked https://github.com/kubedb  ? You can find my contact info on my Github profile, if you want to chat.

-Tamal

**Comment by devdattakulkarni** [comment]
Thanks @tamalsaha 

Will check it out soon.

**Comment by devdattakulkarni** [comment]
Hi Tamal,

I looked at Kubedb. It seems cool!

We were looking for using it for one of our clients. However, they need Percona, which is not yet supported in kubedb (as you mentioned on https://github.com/kubedb/project/issues/169). Also, the fact that kubedb installs crds for all the databases at the setup time makes it bit less attractive to us at this time (I saw this in one of the .sh files which I can't seem to find it now).
That said, we also need volume backups and for that we are looking to use stash (https://github.com/appscode/stash)

Closing the issue as exploration of Kubedb is complete.

- Devdatta
