### ISSUE TITLE
Running the postgres operator without minikube

### ISSUE THREAD

**Issue by danielpygo** [cloud-ark/kubeplus#33]
My set up is that I have a GCE node up and running kubernetes. I followed this tutorial and cloned kubernetes source code into my $GOPATH. At that point I ran hack/local-up-cluster.sh, which runs the kubernetes cluster.
https://dzone.com/articles/easy-step-by-step-local-kubernetes-source-code-cha

I had an issue with running the operator:
go run *.go -kubeconfig=$HOME/.kube/config

It just complains by saying File not found: config.
While running on minikube, this works fine because minikube puts the file in the .kube directory, but when running an actual kubernetes cluster, I did not find it in the .kube directory.

I found the location of the config file in the $KUBECONFIG environment variable.

go run *.go -kubeconfig=$KUBECONFIG
worked just fine for me

![image](https://user-images.githubusercontent.com/11185590/43439099-0f3b48e2-9457-11e8-8fc6-7ee1cdb56b3e.png)

I also set the MINIKUBE_IP variable to the IP of my server, (in controller.go) to 35.196.46.32 which i got from my gcp console

**Comment by devdattakulkarni** [comment]
Thanks for the issue @danielpygo 

Can you also update the issue with what did you do with the MINIKUBE_IP in controller.go? What IP did you use instead of MINIKUBE_IP?

**Comment by danielpygo** [comment]
ah yes, I set it to the ip of my node 35.196.46.32. Hardcoding it may not be a great long term idea because i believe the node ip may change

**Comment by devdattakulkarni** [comment]
Fixed.
