### ISSUE TITLE
kubectl annotate error

### ISSUE THREAD

**Issue by devdattakulkarni** [cloud-ark/kubeplus#625]
When trying kubeplus with Redislab Operator (https://github.com/RedisLabs/redis-enterprise-k8s-docs), seeing following issue:

when i tried to annotate it with the example in your page i got error
kubectl annotate crd redisenterpriseclusters.app.redislabs.com resource/composition="StatefulSet, Service, PodDisruptionBudget"
+ kubectl annotate crd redisenterpriseclusters.app.redislabs.com resource/composition=StatefulSet, Service, PodDisruptionBudget
error: all resources must be specified before annotation changes: Service,
any idea why this error?

They I tried only kubectl annotate crd redisenterpriseclusters.app.redislabs.com resource/composition=StatefulSet and then the plugin worked OK on the CR and it descovered automatically sts\pod\service and even deployment that was related, also PVC related. output attached.

Ref: https://cloud-native.slack.com/archives/D01FPTGS2JF/p1606569402020500

**Comment by devdattakulkarni** [comment]
+ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.404", GitCommit:"81e2afbf51b876d15f0af546998c670207fdd592", GitTreeState:"clean", BuildDate:"2020-10-30T23:52:44Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by devdattakulkarni** [comment]
@shay-berman I tried annotating the RedisLabs crd and did not run into above error. I am on 1.15 version for the Server.
Is it possible for you to try with 1.15 version to see if you still see this error?


```
kubectl annotate crd redisenterpriseclusters.app.redislabs.com resource/composition="StatefulSet, Service, PodDisruptionBudget"
customresourcedefinition.apiextensions.k8s.io/redisenterpriseclusters.app.redislabs.com annotated

kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.20", GitCommit:"0ac5f81eecab42bff5ef74f18b99d8896ba7b89b", GitTreeState:"clean", BuildDate:"2020-09-09T00:48:20Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by devdattakulkarni** [comment]
I am going to close this issue as this point is also being tracked as part of https://github.com/cloud-ark/kubeplus/issues/627

**Comment by shay-berman** [comment]
@devdattakulkarni it happen to me on gke 1.16.

**Comment by devdattakulkarni** [comment]
Thanks. We will track this as part of #627.
