### ISSUE TITLE
Cloning repo failed, Repo size is too large

### ISSUE THREAD

**Issue by mikosa** [cloud-ark/kubeplus#700]
I tried to clone kubeplus repo in gcloud shell but failed due to the size of the repo.
Note that my shell already has stuff there. But this is the first time i get this. So maybe others have same issue too.

```
git clone https://github.com/cloud-ark/kubeplus
Cloning into 'kubeplus'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (36/36), done.
fatal: write error: No space left on deviceiB | 25.10 MiB/s   
fatal: index-pack failed

```

Cloning to my PC actually showed a repo almost 3GB in size
```
git clone https://github.com/cloud-ark/kubeplus.git
Cloning into 'kubeplus'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (36/36), done.

Receiving objects: 100% (7489/7489), 2.96 GiB | 10.89 MiB/s, done.
Resolving deltas: 100% (3736/3736), done.
Updating files: 100% (495/495), done.

```
Maybe need to move all png and tar files to another repo

**Comment by mikosa** [comment]
gcloud shell size is 5GB 
https://cloud.google.com/shell/docs/how-cloud-shell-works#:~:text=Cloud%20Shell%20provisions%205%20GB,on%20the%20virtual%20machine%20instance.

**Comment by devdattakulkarni** [comment]
ack @mikosa

**Comment by devdattakulkarni** [comment]
Turns out that the .git/objects has become large. While we fix this in the mean time use shallow clone.

```git clone --depth 1 https://github.com/cloud-ark/kubeplus.git```
