### ISSUE TITLE
steps.txt deploys crds before creating the cluster

### ISSUE THREAD

**Issue by mikosa** [cloud-ark/kubeplus#703]
documentation for Multiple application stacks deploys the CRDs before creating the cluster

https://github.com/cloud-ark/kubeplus/blob/03e99308d0f78e69b90aecccd584d30ea5515414/examples/multitenancy/stacks/steps.txt#L12

need to move this step after creating the cluster

**Comment by devdattakulkarni** [comment]
Good catch.
