### ISSUE TITLE
example multitenancy team pod error

### ISSUE THREAD

**Issue by mikosa** [cloud-ark/kubeplus#707]
when trying to deploy the following example
```
kubeplus/examples/multitenancy/team/
```

the tenantservice.yaml 
and tenant1.yaml  
Both deploy as expected.

But when adding the ns1pod.yaml file, it fails at init container:
```
$ kubectl get pods -n ns1
NAME      READY   STATUS                  RESTARTS   AGE
nginxp1   0/1     Init:CrashLoopBackOff   5          5m30s
```

there is a configuration issue of the pod.
But the resource policy is applied to the pod as expected.

```
mike@cloudshell:~$ kubectl logs nginxp1     -n ns1 -c install
Connecting to kubernetes.io (147.75.40.148:80)
Connecting to kubernetes.io (147.75.40.148:443)
wget: note: TLS certificate validation not implemented
wget: TLS error from peer (alert code 80): 80
wget: error getting response: Connection reset by peer
```

**Comment by devdattakulkarni** [comment]
I bet this is because the image name is not correct here:
https://github.com/cloud-ark/kubeplus/blob/master/examples/multitenancy/team/ns1pod.yaml#L9

In ns2 did the Pod start correctly?
