### ISSUE TITLE
Feature request: Replace metrics-server with alternative metrics scraping

### ISSUE THREAD

**Issue by mgj** [cloud-ark/kubeplus#778]
Currently KubePlus currently uses metrics-server (https://github.com/kubernetes-sigs/metrics-server) for its metrics scraping needs. This appears to be a problem, because metrics-server itself warns against using it for anything that is not auto-scaling:

```
Metrics Server is not meant for non-autoscaling purposes. For example, don't use it to forward metrics to monitoring solutions, or as a source of monitoring solution metrics.
```
- https://github.com/kubernetes-sigs/metrics-server/blob/master/README.md

Prometheus appears to be a very common component for metrics scraping and it does not rely on metrics-server. Perhaps KubePlus should use prometheus instead?

I was told that KubePlus already uses cadvisor and it also can do its own cpu/memory scraping without relying on metrics-server. Perhaps also an option

**Comment by devdattakulkarni** [comment]
@mgj We have now updated KubePlus to query kubelet for collecting Pod metrics. This removes KubePlus's dependency from  metrics api server.

Whenever you get a chance please give it a try. Let us know how it goes. I will close the issue for now. Please reopen the issue if needed.

**Comment by devdattakulkarni** [comment]
@mgj Hi!
We are starting KubePlus community meetings next week. They will be on Tuesdays at 10.30 a.m. US Central time. The meetings will be on #kubeplus Slack channel in the CNCF workspace. I hope you are able to join us for these meetings as we look forward to building KubePlus further with community inputs and involvement.
