### ISSUE TITLE
python3: can't open file 'connections.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by iplaxton** [cloud-ark/kubeplus#786]
While following the instructions in part 5 of the cluster-installation-and-discovery module, I experienced the following error:
------ Branch 7 ------
Level:0 kind:Namespace name:kube-system
Level:1 kind:Pod name:storage-provisioner [related to Namespace/kube-system by:specproperty]
Level:2 kind:ServiceAccount name:storage-provisioner [related to Pod/storage-provisioner by:specproperty]
Opens-MacBook-Air:cluster-installation-and-discovery iris$ kubectl connections Namespace kube-system kube-system -o png
python3: can't open file 'connections.py': [Errno 2] No such file or directory
Output available in: /Users/iris/plugins/connections-op.json.gv.png
Opens-MacBook-Air:cluster-installation-and-discovery iris$

**Comment by devdattakulkarni** [comment]
@iplaxton I can confirm that this is an issue.

We will fix it soon and update the plugins. Stay tuned.

**Comment by devdattakulkarni** [comment]
@iplaxton Please download latest kubeplus kubectl plugins tar gz and try. Let me know if you are still seeing any problems. In that case open a new issue.

**Comment by iplaxton** [comment]
> While following the instructions in part 5 of the cluster-installation-and-discovery module, I experienced the following error:
> ------ Branch 7 ------
> Level:0 kind:Namespace name:kube-system
> Level:1 kind:Pod name:storage-provisioner [related to Namespace/kube-system by:specproperty]
> Level:2 kind:ServiceAccount name:storage-provisioner [related to Pod/storage-provisioner by:specproperty]
> Opens-MacBook-Air:cluster-installation-and-discovery iris$ kubectl connections Namespace kube-system kube-system -o png
> python3: can't open file 'connections.py': [Errno 2] No such file or directory
> Output available in: /Users/iris/plugins/connections-op.json.gv.png
> Opens-MacBook-Air:cluster-installation-and-discovery iris$

-------------------------------------------
Update:  Yes, the fix works.  Thank you.

**Comment by iplaxton** [comment]
> @iplaxton Please download latest kubeplus kubectl plugins tar gz and try. Let me know if you are still seeing any problems. In that case open a new issue.

@devdattakulkarni It works... thanks!
