### ISSUE TITLE
Issues running on EKS

### ISSUE THREAD

**Issue by nadirhamid** [cloud-ark/kubeplus#788]
Hello,

I have not been able to successfully deploy KubePlus on EKS. I am currently having some issues with the certificates and KubePlus (helmer for example). I have included some of my findings below. There is a log file specific to the error - you may find more info there. I have also included basic details such as the type of KubePlus request and my hostname.

Host name:
ip-xxx-xxx-xx-xxxx.ca-central-1.compute.internal
(real IP is redacted)

KubePlus request:
{
  "requests": {
    "cpu": "200m",
    "memory": "1Gi"
  }
}

You will find more info about the error itself in the log. It seems to be related to certificates but I cannot tell for sure.
I am hoping you will fix this issue as I have been trying to test on Amazon EKS to no avail.

If I can add anything else to further help you debug let me know.

If you have any questions let me know.

Thanks
[eks-trace.txt](https://github.com/cloud-ark/kubeplus/files/6256205/eks-trace.txt)

**Comment by devdattakulkarni** [comment]
There have been several updates made to KubePlus. It now works on EKS.
