### ISSUE TITLE
prep-kube-env-windows.sh Error

### ISSUE THREAD

**Issue by rudragarg** [cloud-ark/kubeplus#793]
When ssh'ed into Vagrant and running ./prep-kube-env-windows.sh, I am getting the following error: 

```
mv: cannot stat '/vagrant/.kube/config': No such file or directory
./prep-kube-env-windows.sh: line 4: /vagrant/.kube/config: No such file or directory
sed: can't read /vagrant/.kube/config.orig: No such file or directory
cp: cannot stat '/vagrant/.kube': No such file or directory
```

These paths do not exist on my machine. 

Is there an installation step that I am missing? What can I do to resolve this issue?

**Comment by devdattakulkarni** [comment]
@rudragarg Have you started the minikube cluster (minikube start) from your Windows Machine?

The .kube directory will be created once you start the cluster.

The prep-kube-env-windows.sh assumes the existence of .kube directory on the host machine.

**Comment by devdattakulkarni** [comment]
@rudragarg Have you started the minikube cluster (minikube start) from your Windows Machine?

The .kube directory will be created once you start the cluster.

The prep-kube-env-windows.sh assumes the existence of .kube directory on the host machine.

**Comment by devdattakulkarni** [comment]
@rudragarg Also, make sure that you are running minikube start from the same folder where you have saved the Vagrantfile.

**Comment by devdattakulkarni** [comment]
@rudragarg Is this still an issue?

**Comment by rudragarg** [comment]
Running the script is not an issue anymore.
