### ISSUE TITLE
missing image repo in /deploy/rc.yaml

### ISSUE THREAD

**Issue by kalise** [cloud-ark/kubeplus#88]
- name: etcd
        image: quay.io/coreos/etcd:v3.2.18
      - name: operator-manager                            
        image: operator-manager:latest         <--
        imagePullPolicy: Never

**Comment by devdattakulkarni** [comment]
@kalise Thanks for catching this. Let me check the details and get back to you asap.

**Comment by devdattakulkarni** [comment]
@kalise: Did you follow the steps from: https://github.com/cloud-ark/kubeplus/blob/master/kubeplus-steps.txt

Step 19 https://github.com/cloud-ark/kubeplus/blob/master/kubeplus-steps.txt#L19 

builds the operator-manager docker image. Did that step fail?

**Comment by kalise** [comment]
@devdattakulkarni no just started with the README. Yous should update it, please.

Thanks

```
1) Install KubePlus (by cluster administrator)

KubePlus requires Helm to be installed on the cluster.

Install Helm:

$ helm init
Once tiller pod is Running (kubectl get pods -n kube-system), install KubePlus. We provide deployment YAMLs for deploying KubePlus.

$ kubectl apply -f deploy/
...

```

**Comment by devdattakulkarni** [comment]
@kalise: Thanks! I will update the README.

For a real Kubernetes cluster the steps are similar. The rc.yaml file will have to be changed to pull images from docker hub. I will update asap today. Stay tuned.
Will drop a note here once done.

**Comment by kalise** [comment]
Still issues while building

`./buildall.sh 
Building Operator Manager
rm: cannot remove 'operator-manager/operator-manager': No such file or directory
Error response from daemon: No such image: operator-manager:latest
`

**Comment by devdattakulkarni** [comment]
README is updated. 
Looking into other points. Stay tuned.

**Comment by kalise** [comment]
@devdattakulkarni Thanks!

**Comment by devdattakulkarni** [comment]
@kalise I have updated the steps with more details and tweaked the build script. 
Please pull master and try.

The build script builds required Docker images. This may take some time depending on your network. 

The overall steps are still for Minikube. So make sure you install Minikube and run the eval command (https://github.com/cloud-ark/kubeplus/blob/master/kubeplus-steps.txt#L15) so that locally built Docker images will be correctly used. Run the eval command before running the build script.

Let me know how it goes.

**Comment by devdattakulkarni** [comment]
@kalise I have pushed several updates today (including changes to rc.yaml that uses images from Docker hub). Now it is not required to build KubePlus images locally. 
Please pull master and give it a try. Follow the steps in:
https://github.com/cloud-ark/kubeplus/blob/master/kubeplus-steps.txt

I have also recorded a demo video.  Here is the link:
https://drive.google.com/file/d/1jDptIWM8fiAorlZdW-pwOMttxAQAZHIR/view

Let me know how it goes.

**Comment by kalise** [comment]
@devdattakulkarni I was able to follow the tutorial as in the video and it worked. One question: why you need helm (and tiller) to install the operator? I'm asking because I would dispose of both of them and use only kubectl command to install everything.

Good work, man!

**Comment by devdattakulkarni** [comment]
@bsctl Hi!
We are starting KubePlus community meetings next week. They will be on Tuesdays at 10.30 a.m. US Central time. The meetings will be on #kubeplus Slack channel in the CNCF workspace. I hope you are able to join us for these meetings as we look forward to building KubePlus further with community inputs and involvement.
