### ISSUE TITLE
stripe payment / saas

### ISSUE THREAD

**Issue by ghost** [cloud-ark/kubeplus#943]
Hi guys,

Hope you are all well !

I was wondering if you have on your roadmap a payment gateway for deploying wordpress instances on paid basis.

It would be awesome also for providing multi-tenant machine learning services.

Thanks for any insights or inputs on that idea.

Cheers,
Luc Michalski

**Comment by devdattakulkarni** [comment]
Hi @lucmichalski 

Thanks for the questions.

Payment gateway integration within Wordpress Service example is a great idea. Is there any particular payment gateway you are working with? As long as there is a containerized version of the payment gateway integration available (say, a containerized Stripe connector), it should be possible to enhance the Wordpress Helm chart to include it. That is all which is needed to integrate a payment gateway with the Wordpress Service. Let us know which payment gateway you are working with and we will be happy to get you started. 

About machine learning services - yes, that is something we have considered. Is there any particular ML example service that you are interested in? Let us know and together we can look into developing that example for KubePlus. 

The main requirement to create a multi-tenant service via KubePlus is to start with an application's Helm chart. Once that is there, the rest of the parts like creating separate application instances in separate namespaces, enforcing cpu/memory requests and limits on the application Pods, etc. are automated by KubePlus.

Let us know if above helps clarify your questions. If not, feel free to follow up here or reach out to us on our slack channel.

Regards,
Devdatta

**Comment by lucmichalski** [comment]
Hi,

Thanks for the quick reply !

I was looking at this example using stripe payment gateway: https://github.com/x0rzkov/KubeML

There is also a support for deploying Jupyter notebooks for ml usage.

What do you think ? Is it doable ?
![recording-1](https://user-images.githubusercontent.com/1963546/134905934-7966f672-7fe4-443b-bab0-603aaa9c3b97.gif)



Cheers,
Luc Michalski

**Comment by devdattakulkarni** [comment]
Hi @lucmichalski 
I checked the README of that project. Based on it I would say it should be possible to do something like KubeML through KubePlus. The main thing needed to use KubePlus is the application Helm chart. In this case you would need a Helm chart that contains the required Jupyter assets (eg.: Jupyter Notebook container/Jupyter Enterprise gateway) and a container for Stripe integration. Please reach out to me over email (devdatta at cloudark dot io) and we can setup a time to discuss more details about your exact requirements.

**Comment by devdattakulkarni** [comment]
@lucmichalski Unfortunately I do not have a telegram account. But we have a Slack channel that you can join may be? Or if it is convenient, email will also work.

**Comment by lucmichalski** [comment]
slack is fine :-) as soon as they fix their root certificate problem

https://twitter.com/SlackStatus/status/1443612591406780424
